### ISSUE TITLE
拖动问题

### ISSUE THREAD

**Issue by Stevezhong0506** [tt3tt3tt/SCButton#1]
你好，我的viewcontroller有一个tableview,然后再把disView加进去之后就不能拖到disview移动了，用bringSubviewToFront的话，disview视图直接不见了，是什么原因呢？然后我把disView的宽高调大到100，手指在圈内的上半部分地方又可以拖动，是frame的问题么

**Comment by Archerlly** [comment]
抱歉,由于最近工作有点忙,没注意这边,问题应该是手势的响应循序,tableView的手势处理优先于disView的pan手势,你可以用requireGestureRecognizerToFail去调整一下,希望能帮上你.

**Comment by jaccty** [comment]
请问在IOS7.1.2上横屏情况下无法拖动，竖屏正常，为什么呢？能解决下这个BUG吗？

**Comment by Archerlly** [comment]
@jaccty 在切换横竖屏的时候, 你需要修改borderRect这个属性, 才能保证其正常拖动与正确计算边界

**Comment by SuperManPLA** [comment]
如果按钮数量过多，比如10个，在小屏幕上将按钮拖到底部，展开的时候就会crash，应该是地方不够展开导致的

**Comment by SuperManPLA** [comment]
我通过添加一个计数值判断如果递归的次数大于 button的总数量乘以100，我就跳出递归，输出错误提示，避免了crash，有更好的方法吗

**Comment by Archerlly** [comment]
@SuperManPLA 你这确实是个好办法, 我认为在进行递归计算之前可以用最大的展示区域进行一次对比检查, 可以保证递归一定有结果. 有空我尝试一下这个想法, 多谢你的指正.
